---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "gmod.fullname" . }}-update
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "update.txt").AsConfig | indent 2 }}
