---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gmod.fullname" . }}
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "gmod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gmod.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gmod.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: gmod
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: gmod-server-tcp
              containerPort: 27015
              protocol: TCP
            - name: gmod-server-udp
              containerPort: 27015
              protocol: UDP
          env:
            - name: TZ
              value: {{ .Values.properties.timezone | quote }}
            - name: INSTALL_CSS
              value: {{ .Values.properties.installCSS | quote }}
            - name: INSTALL_HL2
              value: {{ .Values.properties.installHL2 | quote }}
            - name: INSTALL_HLDM
              value: {{ .Values.properties.installHLDM | quote }}
            - name: INSTALL_TF2
              value: {{ .Values.properties.installTF2 | quote }}
            - name: WORKSHOP_COLLECTION_ID
              value: {{ .Values.properties.workshopCollectionID | quote }}
            - name: SERVER_NAME
              value: {{ .Values.properties.serverName | quote }}
            - name: SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gmod.fullname" . }}-server-password
                  key: password
            - name: SERVER_RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gmod.fullname" . }}-rcon-password
                  key: password
            - name: SERVER_DEFAULT_MAP
              value: {{ .Values.properties.defaultMap | quote }}
            - name: SERVER_MAX_PLAYERS
              value: {{ .Values.properties.maxPlayers | quote }}
            - name: SERVER_GAMEMODE
              value: {{ .Values.properties.gamemode | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: savedata
              mountPath: /home/steam/serverfiles
      volumes:
        - name: savedata
          persistentVolumeClaim:
            claimName: {{ include "gmod.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
