---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gmod.fullname" . }}
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gmod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gmod.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: gmod
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["/home/gmod/start.sh"]
          ports:
            - name: gmod-server
              containerPort: 27015
            - name: gmod-client
              containerPort: 27005
          livenessProbe:
            exec:
              command:
                - bash
                - /home/gmod/health.sh
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - bash
                - /home/gmod/health.sh
            initialDelaySeconds: 0
            periodSeconds: 10
          env:
            - name: PRODUCTION
              value: {{ .Values.production | quote }}
            - name: MAXPLAYERS
              value: {{ .Values.maxPlayers | quote }}
            - name: GAMEMODE
              value: {{ .Values.gamemode | quote }}
            - name: MAP
              value: {{ .Values.map | quote }}
            - name: ARGS
              value: {{ .Values.args | quote }}
          volumeMounts:
            - name: update-script
              subPath: update.txt
              mountPath: /home/gmod/update.txt
            - name: users-list
              subPath: users.txt
              mountPath: /home/gmod/server/garrysmod/settings/users.txt
      {{- if .Values.mapsDir }}
            - name: maps-dir
              mountPath: /home/gmod/server/garrysmod/maps
      {{- end }}
      {{- if .Values.addonsDir }}
            - name: addons-dir
              mountPath: /home/gmod/server/garrysmod/addons
      {{- end }}
      volumes:
        - name: users-list
          configMap:
            name: {{ include "gmod.fullname" . }}-users
            defaultMode: 0644
        - name: update-script
          configMap:
            name: {{ include "gmod.fullname" . }}-update
            defaultMode: 0644
      {{- if .Values.mapsDir }}
        - name: maps-dir
          hostPath:
            path: {{ .Values.mapsDir }}
            type: Directory
      {{- end }}
      {{- if .Values.addonsDir }}
        - name: addons-dir
          hostPath:
            path: {{ .Values.addonsDir }}
            type: Directory
      {{- end }}
