---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gmod.fullname" . }}
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gmod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gmod.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gmod.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: gmod
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/home/gmod/start.sh"]
          ports:
            - name: gmod-server-tcp
              containerPort: 27015
              protocol: TCP
            - name: gmod-server-udp
              containerPort: 27015
              protocol: UDP
            - name: gmod-client
              containerPort: 27005
          livenessProbe:
            exec:
              command:
                - bash
                - /home/gmod/health.sh
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - bash
                - /home/gmod/health.sh
            initialDelaySeconds: 0
            periodSeconds: 10
          env:
            - name: PRODUCTION
              value: {{ .Values.properties.production | quote }}
            - name: MAXPLAYERS
              value: {{ .Values.properties.maxPlayers | quote }}
            - name: GAMEMODE
              value: {{ .Values.properties.gamemode | quote }}
            - name: MAP
              value: {{ .Values.properties.map | quote }}
            - name: ARGS
              value: {{ .Values.properties.args | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
