---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gmod.fullname" . }}
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gmod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gmod.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: gmod
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: gmod
              containerPort: 27015
          env:
            - name: PRODUCTION
              value: {{ .Values.production | quote }}
            - name: MAXPLAYERS
              value: {{ .Values.maxPlayers | quote }}
            - name: GAMEMODE
              value: {{ .Values.gamemode | quote }}
            - name: MAP
              value: {{ .Values.map | quote }}
      {{- if .Values.mapsDir }}
          volumeMounts:
            - name: maps-dir
              mountPath: /home/gmod/server/garrysmod/maps
      {{- end }}
      {{- if .Values.mapsDir }}
      volumes:
        - name: maps-dir
          hostPath:
            path: {{ .Values.mapsDir }}
            type: Directory
      {{- end }}
