---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gmod.fullname" . }}-rcon-password
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "gmod.rconPassword" . | b64enc | quote }}
