---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gmod.fullname" . }}
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: gmod-server-tcp
      protocol: TCP
      port: 27015
      {{- if .Values.serverPort }}
      nodePort: {{ .Values.serverPort }}
      {{- end }}
    - name: gmod-server-udp
      protocol: UDP
      port: 27015
      {{- if .Values.serverPort }}
      nodePort: {{ .Values.serverPort }}
      {{- end }}
  selector:
    {{- include "gmod.selectorLabels" . | nindent 4 }}
