---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gmod.fullname" . }}
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  selector:
    {{- include "gmod.selectorLabels" . | nindent 4 }}
  ports:
    - name: gmod-server-tcp
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: gmod-server-tcp
    - name: gmod-server-udp
      protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: gmod-server-udp
