---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gmod.fullname" . }}
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "gmod.selectorLabels" . | nindent 4 }}
  ports:
    - name: gmod-server
      protocol: UDP
      port: 27015
      {{- if .Values.serverPort }}
      nodePort: {{ .Values.serverPort }}
      {{- end }}
    - name: gmod-client
      protocol: UDP
      port: 27005
      {{- if .Values.serverPort }}
      nodePort: {{ add .Values.serverPort 1 }}
      {{- end }}
