---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gmod.fullname" . }}
  labels:
    {{- include "gmod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gmod.selectorLabels" . | nindent 4 }}
  ports:
    - name: gmod-server-tcp
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: gmod-server-tcp
    - name: gmod-server-udp
      protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: gmod-server-udp
