---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: friendbot
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: friendbot
              containerPort: 6000
          env:
            {{ if .Values.redis.host }}
            - name: FRIENDBOT_REDIS_HOST
              value: "{{ .Values.redis.host }}"
            {{- end }}
            {{ if .Values.redis.port }}
            - name: FRIENDBOT_REDIS_PORT
              value: "{{ .Values.redis.port }}"
            {{- end }}
            {{ if .Values.logLevel }}
            - name: FRIENDBOT_LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            {{- end }}
            {{ if .Values.exportLocation }}
            - name: FRIENDBOT_EXPORT_ZIP
              value: /friendbot/export.zip
            {{- else }}
            - name: FRIENDBOT_EXPORT_ZIP
              value: /test-export.zip
            {{- end }}
            {{ if .Values.signature }}
            - name: FRIENDBOT_SECRET_FILE
              value: /friendbot-secret/signature
            {{- end }}
          volumeMounts:
            {{ if .Values.exportLocation }}
            - name: {{ .Release.Name }}-export
              mountPath: /friendbot/export.zip
            {{- end }}
            {{ if .Values.signature }}
            - name: {{ .Release.Name }}-signature
              mountPath: /friendbot-secret
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: friendbot
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: friendbot
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        {{ if .Values.exportLocation }}
        - name: {{ .Release.Name }}-export
          hostPath:
            path: {{ .Values.exportLocation }}
            type: File
        {{- end }}
        {{ if .Values.signature }}
        - name: {{ .Release.Name }}-signature
          secret:
            secretName: {{ .Release.Name }}-signature
        {{- end }}
