---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "friendbot.fullname" . }}
  labels:
    {{- include "friendbot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "friendbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "friendbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "friendbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: friendbot
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: friendbot
              containerPort: 8000
              protocol: TCP
          env:
            - name: FRIENDBOT_LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: FRIENDBOT_EXPORT_ZIP
              value: /home/friendbot/export.zip
            {{- if .Values.signature }}
            - name: FRIENDBOT_SECRET_FILE
              value: /friendbot-secret/signature
            {{- end }}
            - name: FRIENDBOT_REDIS_HOST
              value: {{ include "friendbot.redisHost" . | quote }}
            - name: FRIENDBOT_REDIS_PORT
              value: {{ include "friendbot.redisPort" . | quote }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: friendbot
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /metrics
              port: friendbot
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.exportLocation }}
            - name: export
              mountPath: /home/friendbot/export.zip
            {{- end }}
            {{- if .Values.signature }}
            - name: signature
              mountPath: /friendbot-secret
            {{- end }}
      volumes:
        {{- if .Values.exportLocation }}
        - name: export
          hostPath:
            path: {{ .Values.exportLocation }}
            type: File
        {{- end }}
        {{- if .Values.signature }}
        - name: signature
          secret:
            secretName: {{ include "friendbot.fullname" . }}-signature
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
