---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "friendbot.fullname" . }}
  labels:
    {{- include "friendbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "friendbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "friendbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: friendbot
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: friendbot
              containerPort: 8000
          env:
            {{- if .Values.redis.host }}
            - name: FRIENDBOT_REDIS_HOST
              value: "{{ .Values.redis.host }}"
            {{- end }}
            {{- if .Values.redis.port }}
            - name: FRIENDBOT_REDIS_PORT
              value: "{{ .Values.redis.port }}"
            {{- end }}
            {{- if .Values.logLevel }}
            - name: FRIENDBOT_LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            {{- end }}
            {{- if .Values.exportLocation }}
            - name: FRIENDBOT_EXPORT_ZIP
              value: /friendbot/export.zip
            {{- else }}
            - name: FRIENDBOT_EXPORT_ZIP
              value: /test-export.zip
            {{- end }}
            {{- if .Values.signature }}
            - name: FRIENDBOT_SECRET_FILE
              value: /friendbot-secret/signature
            {{- end }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: friendbot
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /metrics
              port: friendbot
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 150m
              memory: 150Mi
      {{- if or .Values.exportLocation .Values.signature }}
          volumeMounts:
            {{- if .Values.exportLocation }}
            - name: {{ .Release.Name }}-export
              mountPath: /friendbot/export.zip
            {{- end }}
            {{- if .Values.signature }}
            - name: {{ .Release.Name }}-signature
              mountPath: /friendbot-secret
            {{- end }}
      volumes:
        {{- if .Values.exportLocation }}
        - name: {{ .Release.Name }}-export
          hostPath:
            path: {{ .Values.exportLocation }}
            type: File
        {{- end }}
        {{- if .Values.signature }}
        - name: {{ .Release.Name }}-signature
          secret:
            secretName: {{ include "friendbot.fullname" . }}-signature
        {{- end }}
      {{- end }}
