{{ if .Values.signature }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-signature
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  signature: "{{ .Values.signature }}"
{{- end }}
