{{ if .Values.signature }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "friendbot.fullname" . }}-signature
  labels:
    {{- include "friendbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  signature: "{{ .Values.signature }}"
{{- end }}
