---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "friendbot.fullname" . }}
  labels:
    {{- include "friendbot.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "friendbot.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8000
      targetPort: friendbot
      protocol: TCP
