---
metrics: true
persistence:
  size: 10Gi
  storageClassName: longhorn
podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 111
public: true
resources:
  limits:
    memory: 4000Mi
  requests:
    cpu: 700m
    memory: 3000Mi
serverName: Barrelmaker
service:
  port: 2456
  type: LoadBalancer
worldName: Asgard
