---
# Must be in the range 30000-32767
serverPort: "30001"
dynmap: false
metrics: true
saveLocation: /home/barrelmaker/gamedata/minecraft
properties:
  difficulty: "normal"
  ops: "Barrelmaker97"
  memory: "2G"
  serverName: "Primordial"
  motd: "Primordial Server"
  spawnProtection: "0"
  forceGamemode: "true"
  viewDistance: "32"
  type: "BUKKIT"
  timezone: "America/Chicago"
