---
# Must be in the range 30000-32767
serverPort: "30001"
dynmap: false
metrics: true
saveLocation: /home/barrelmaker/gamedata/minecraft
properties:
  memory: "2G"
  motd: "Primordial Server"
  ops: "Barrelmaker97"
  serverName: "Primordial"
  type: "BUKKIT"
  viewDistance: "32"
