---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "serge.fullname" . }}-data
  labels:
    {{- include "serge.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.data.storageClassName }}
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.persistence.data.size }}
