---
chart-repos: bitnami=https://charts.bitnami.com/bitnami,minio=https://charts.min.io/,valkey=https://valkey.io/valkey-helm/
excluded-charts: pistachio
remote: origin
target-branch: main
upgrade: true
