---
chart-repos: bitnami=https://charts.bitnami.com/bitnami,minio=https://charts.min.io/
check-version-increment: true
remote: origin
target-branch: main
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
