---
check-version-increment: true
chart-repos: bitnami=https://charts.bitnami.com/bitnami
remote: origin
target-branch: main
upgrade: true
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
