---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: jellyfin
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: jellyfin
              containerPort: 8096
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /media
            - name: {{ .Release.Name }}-cache
              mountPath: /cache
            - name: {{ .Release.Name }}-config
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /
              port: jellyfin
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: jellyfin
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: {{ .Release.Name }}-data
          {{- if .Values.remoteLibrary }}
          nfs:
            server: soteria.lan
            path: /volume1/local_only/content/media
          {{- else }}
          hostPath:
            path: /home/barrelmaker/{{ .Release.Name }}-data
            type: DirectoryOrCreate
          {{- end }}
        - name: {{ .Release.Name }}-cache
          emptyDir:
            medium: "Memory"
        - name: {{ .Release.Name }}-config
          hostPath:
            path: /home/barrelmaker/{{ .Release.Name }}-config
            type: DirectoryOrCreate
