---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-media
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClassName.media }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
