---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
  ports:
    - name: jellyfin
      protocol: TCP
      port: 8096
      targetPort: 8096
