---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "starbound.fullname" . }}
  labels:
    {{- include "starbound.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "starbound.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "starbound.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "starbound.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: starbound
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ['sh', '-c', 'yes']
          env:
            - name: SKIP_STEAMCMD
              value: "True"
          # - name: STEAM_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ include "starbound.fullname" . }}-steam-creds
          #       key: password
          # - name: STEAM_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ include "starbound.fullname" . }}-steam-creds
          #       key: username
          ports:
            - name: starbound-port
              containerPort: 21025
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.saveLocation }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: /steamcmd/starbound
      volumes:
        - name: "{{ .Release.Name }}-data"
          hostPath:
            path: "{{ .Values.saveLocation }}/{{ .Release.Name }}-data"
            type: DirectoryOrCreate
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
