---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "starbound.fullname" . }}
  labels:
    {{- include "starbound.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "starbound.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "starbound.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: starbound
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          #command: ['sh', '-c', 'yes']
          env:
            - name: SKIP_STEAMCMD
              value: "True"
          # - name: STEAM_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ include "starbound.fullname" . }}-steam-password
          #       key: password
          # - name: STEAM_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ include "starbound.fullname" . }}-steam-username
          #       key: username
          ports:
            - name: starbound-port
              containerPort: 21025
      {{- if .Values.saveLocation }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: /steamcmd/starbound
      volumes:
        - name: "{{ .Release.Name }}-data"
          hostPath:
            path: "{{ .Values.saveLocation }}/{{ .Release.Name }}-data"
            type: DirectoryOrCreate
      {{- end }}
