---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "starbound.fullname" . }}-steam-password
  labels:
    {{- include "starbound.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "{{ .Values.steamPassword }}"
