---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "starbound.fullname" . }}-steam-username
  labels:
    {{- include "starbound.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.steamUsername }}"
