---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: starbound-port
      protocol: TCP
      port: 21025
      {{- if .Values.serverPort }}
      nodePort: {{ .Values.serverPort }}
      {{- end }}
