---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "starbound.fullname" . }}
  labels:
    {{- include "starbound.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "starbound.selectorLabels" . | nindent 4 }}
  ports:
    - name: starbound-port
      protocol: TCP
      port: 21025
      {{- if .Values.serverPort }}
      nodePort: {{ .Values.serverPort }}
      {{- end }}
