---
image:
  repo: "docker.io"
  name: "itzg/minecraft-server"
  tag: "latest"

storageClassName: ""

properties:
  difficulty: "normal"
  eula: "TRUE"
  forceGamemode: "true"
  gamemode: "suvival"
  motd: "Minecraft Server"
  serverName: "Minecraft Server"
  spawnProtection: "0"
  timezone: "America/Chicago"
  version: "LATEST"
