---
image:
  repo: "docker.io"
  name: "itzg/minecraft-server"
  tag: "latest"
properties:
  eula: "TRUE"
  difficulty: "normal"
  serverName: "Minecraft Server"
  timezone: "America/Chicago"
  motd: "Minecraft Server"
  gamemode: "suvival"
  spawnProtection: "0"
  forceGamemode: "true"
