---
image:
  repository: docker.io/itzg/minecraft-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

persistence:
  storageClassName: ""
  size: 1Gi

# Requires installation of the mod dynmap to work properly
# https://modrinth.com/plugin/dynmap
dynmap:
  enabled: false
  cores: 10
  showOfflinePlayers: false
  showSpawnBeds: false
  config:
    resources: {}
    # requests:
    #   cpu: 10m
    #   memory: 10Mi
    # limits:
    #   cpu: 30m
    #   memory: 30Mi
    securityContext: {}
    # allowPrivilegeEscalation: false
    # capabilities:
    #   drop:
    #     - ALL
  ingress:
    enabled: false
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: minecraft.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: minecraft-tls
    #    hosts:
    #      - minecraft.local

# Requires installation of the mod Prometheus Exporter to work properly
# https://github.com/sladkoff/minecraft-prometheus-exporter
metrics:
  enabled: false
  dashboard:
    enabled: false
    namespace: monitoring
    labels:
      grafana_dashboard: "1"
  serviceMonitor:
    enabled: false
    # Labels to be added to the ServiceMonitor.
    additionalLabels: {}
    # Annotations to be added to the ServiceMonitor.
    annotations: {}
    # Interval at which Prometheus scrapes the metrics from the target.
    scrapeInterval: 15s
    # Preserves the metric’s labels when they collide with the target’s labels.
    # honorLabels: true
    relabelings: []
    metricRelabelings: []
    # The label to use to retrieve the job name from.
    # jobLabel: "app.kubernetes.io/name"
    targetLabels: []
    # Per-scrape limit on number of labels that will be accepted for a sample.
    labelLimit: 0
    # Per-scrape limit on length of labels name that will be accepted for a sample.
    labelNameLengthLimit: 0
    # Per-scrape limit on length of labels value that will be accepted for a sample.
    labelValueLengthLimit: 0
    # Defines a per-scrape limit on the number of scraped samples that will be accepted.
    sampleLimit: 0
    # Defines a limit on the number of scraped targets that will be accepted.
    targetLimit: 0

properties:
  aikarFlags: false
  difficulty: normal
  enforceWhitelist: false
  eula: "TRUE"
  forceGamemode: true
  gamemode: survival
  memory: 1G
  motd: "Minecraft Server"
  online: "TRUE"
  ops: ""
  existingWhitelist: "SKIP"
  existingOps: "SKIP"
  paperChannel: "default"
  seed: ""
  serverName: "Minecraft Server"
  spawnProtection: 0
  spigetResources: ""
  modrinthProjects: ""
  plugins: ""
  timezone: "America/Chicago"
  type: VANILLA
  version: LATEST
  viewDistance: 10
  whitelist: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# runAsNonRoot: true
# runAsUser: 1000
# runAsGroup: 1000
# fsGroup: 1000

securityContext: {}
# allowPrivilegeEscalation: false
# capabilities:
#   drop:
#     - ALL

service:
  type: ClusterIP
  port: 25565

resources: {}
# requests:
#   cpu: 1000m
#   memory: 1000Mi
# limits:
#   cpu: 1500m
#   memory: 2000Mi

nodeSelector: {}

tolerations: []

affinity: {}
