---
image:
  repository: docker.io/itzg/minecraft-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

persistence:
  storageClassName: ""
  size: 1Gi

# Requires installation of the mod dynmap to work properly
# https://modrinth.com/plugin/dynmap
dynmap: false

# Requires installation of the mod Prometheus Exporter to work properly
# https://github.com/sladkoff/minecraft-prometheus-exporter
metrics: false

properties:
  aikarFlags: false
  difficulty: normal
  enforceWhitelist: false
  eula: "TRUE"
  forceGamemode: true
  gamemode: survival
  memory: 1G
  motd: "Minecraft Server"
  online: "TRUE"
  ops: ""
  existingWhitelist: "SKIP"
  existingOps: "SKIP"
  paperChannel: "default"
  seed: ""
  serverName: "Minecraft Server"
  spawnProtection: 0
  spigetResources: ""
  modrinthProjects: ""
  timezone: "America/Chicago"
  type: VANILLA
  version: LATEST
  viewDistance: 10
  whitelist: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 1000
  # fsGroup: 1000

securityContext: {}
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #     - ALL

resources: {}
  # requests:
  #   cpu: 1000m
  #   memory: 1000Mi
  # limits:
  #   cpu: 1500m
  #   memory: 2000Mi

nodeSelector: {}

tolerations: []

affinity: {}
