---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            {{- if .Values.timezone }}
            - name: TZ
              value: {{ .Values.timezone | quote }}
            {{- end }}
            {{- if .Values.serverName }}
            - name: NAME
              value: {{ .Values.serverName | quote }}
            {{- end }}
            {{- if .Values.worldName }}
            - name: WORLD
              value: {{ .Values.worldName | quote }}
            {{- end }}
            {{- if .Values.public }}
            - name: PUBLIC
              value: "1"
            {{- else }}
            - name: PUBLIC
              value: "0"
            {{- end }}
            {{- if .Values.password }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name}}-password"
                  key: password
            {{- end }}
          ports:
            - name: valheim-1
              containerPort: 2456
            - name: valheim-2
              containerPort: 2457
            - name: valheim-3
              containerPort: 2458
      {{- if .Values.saveLocation }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: /home/steam/.config/unity3d/IronGate/Valheim
              subPath: saves
            - name: "{{ .Release.Name }}-data"
              mountPath: /home/steam/valheim
              subPath: server
      volumes:
        - name: "{{ .Release.Name }}-data"
          hostPath:
            path: "{{ .Values.saveLocation }}/{{ .Release.Name }}-data"
            type: DirectoryOrCreate
      {{- end }}
