---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "valheim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "valheim.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: valheim
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: NAME
              value: {{ .Values.serverName | quote }}
            - name: WORLD
              value: {{ .Values.worldName | quote }}
            {{- if .Values.public }}
            - name: PUBLIC
              value: "1"
            {{- else }}
            - name: PUBLIC
              value: "0"
            {{- end }}
            {{- if .Values.password }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "valheim.fullname" . }}-password
                  key: password
            {{- end }}
            - name: ADDRESS
              value: 127.0.0.1
          ports:
            - name: valheim-1
              containerPort: 2456
            - name: valheim-2
              containerPort: 2457
            - name: valheim-3
              containerPort: 2458
          resources:
            limits:
              cpu: 1000m
              memory: 7Gi
            requests:
              cpu: 700m
              memory: 5Gi
          volumeMounts:
            - name: savedata
              mountPath: /home/steam/.config/unity3d/IronGate/Valheim
              subPath: saves
            - name: savedata
              mountPath: /home/steam/valheim
              subPath: server
      volumes:
        - name: savedata
          persistentVolumeClaim:
            claimName: {{ include "valheim.fullname" . }}
