---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "valheim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "valheim.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "valheim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: valheim
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: NAME
              value: {{ .Values.serverName | quote }}
            - name: WORLD
              value: {{ .Values.worldName | quote }}
            {{- if .Values.public }}
            - name: PUBLIC
              value: "1"
            {{- else }}
            - name: PUBLIC
              value: "0"
            {{- end }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "valheim.fullname" . }}-password
                  key: password
            - name: ADDRESS
              value: 127.0.0.1
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - "pidof valheim_server.x86_64 || exit 1"
            initialDelaySeconds: 60
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - "pidof valheim_server.x86_64 || exit 1"
          ports:
            - name: valheim-1
              containerPort: 2456
            - name: valheim-2
              containerPort: 2457
            - name: valheim-3
              containerPort: 2458
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: savedata
              mountPath: /home/steam/.config/unity3d/IronGate/Valheim
              subPath: saves
            - name: savedata
              mountPath: /home/steam/valheim
              subPath: server
      volumes:
        - name: savedata
          persistentVolumeClaim:
            claimName: {{ include "valheim.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
