---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim.fullname" . }}-password
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "valheim.password" . | b64enc | quote }}
