{{- if .Values.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-password"
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  password: "{{ .Values.signature }}"
{{- end }}
