{{- if .Values.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim.fullname" . }}-password
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "{{ .Values.password }}"
{{- end }}
