{{- $secretName := printf "%s-password" (include "valheim.fullname" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim.fullname" . }}-password
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.password) }}
  password: {{ .Values.password | b64enc | quote }}
  {{ else if (lookup "v1" "Secret" .Release.Namespace $secretName).data }}
  password: {{ (lookup "v1" "Secret" .Release.Namespace $secretName).data.password }}
  {{ else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
