---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "valheim.selectorLabels" . | nindent 4 }}
  ports:
    - name: valheim-1
      protocol: UDP
      port: 2456
      {{- if .Values.serverPort }}
      nodePort: {{ .Values.serverPort }}
      {{- end }}
    - name: valheim-2
      protocol: UDP
      port: 2457
      {{- if .Values.serverPort }}
      nodePort: {{ add .Values.serverPort 1 }}
      {{- end }}
    - name: valheim-3
      protocol: UDP
      port: 2458
      {{- if .Values.serverPort }}
      nodePort: {{ add .Values.serverPort 2 }}
      {{- end }}
