---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "valheim.selectorLabels" . | nindent 4 }}
  ports:
    - name: valheim-1
      protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: valheim-1
    - name: valheim-2
      protocol: UDP
      port: {{ add .Values.service.port 1 }}
      targetPort: valheim-2
    - name: valheim-3
      protocol: UDP
      port: {{ add .Values.service.port 2 }}
      targetPort: valheim-3
