---
issuerName: letsencrypt-prod
baseDomain: barrelmaker.dev
securityHeaders: |-
  add_header X-Frame-Options SAMEORIGIN;
  add_header Referrer-Policy same-origin;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Content-Type-Options nosniff;
