---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "website.fullname" . }}-config
  labels:
    {{- include "website.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "nginx.conf").AsConfig | indent 2 }}
