---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "proxy.fullname" . }}-config
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "nginx.conf").AsConfig | indent 2 }}
