---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: proxy
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: nginx-port
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              subPath: nginx.conf
              mountPath: /etc/nginx/nginx.conf
            {{- if .Values.websiteLocation }}
            - name: {{ .Release.Name }}-website-volume
              mountPath: /usr/share/nginx/html
            {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: nginx-port
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: nginx-port
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: {{ .Release.Name }}-config-volume
          configMap:
            name: {{ include "proxy.fullname" . }}-config
            defaultMode: 0644
        {{- if .Values.websiteLocation }}
        - name: {{ .Release.Name }}-website-volume
          hostPath:
            path: {{ .Values.websiteLocation }}
            type: DirectoryOrCreate
        {{- end }}
