---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.20.1
      containers:
        - name: {{ .Release.Name }}
          image: nginx:alpine
          ports:
            - name: nginx-port
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: {{ .Release.Name }}-data-volume
              subPath: nginx/nginx.conf
            - mountPath: /etc/nginx/conf.d
              name: {{ .Release.Name }}-data-volume
              subPath: nginx/servers
            - mountPath: /var/www/website
              name: {{ .Release.Name }}-data-volume
              subPath: website
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: nginx-port
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: nginx-port
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: {{ .Release.Name }}-data-volume
          hostPath:
            path: /home/barrelmaker/git/nginx-certbot/data
            type: Directory
