---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
