---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-custom-headers
data:
  Content-Security-Policy: "frame-ancestors 'self'; default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self'; connect-src 'self' https://grafana.com; img-src 'self' data:; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self';"
