---
apiVersion: v1
kind: Endpoints
metadata:
  name: grafana-external
subsets:
  - addresses:
      - ip: {{ $.Values.grafana.ip }}
    ports:
      - name: http
        port: {{ $.Values.grafana.port }}
        protocol: TCP
