---
apiVersion: v1
kind: Endpoints
metadata:
  name: kuma-external
subsets:
  - addresses:
      - ip: {{ $.Values.kuma.ip }}
    ports:
      - name: http
        port: {{ $.Values.kuma.port }}
        protocol: TCP
