---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factorio-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuerName }}
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header Content-Security-Policy "frame-ancestors 'self'; default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; base-uri 'self'; form-action 'self';" always;
spec:
  ingressClassName: {{ $.Values.ingressClass }}
  tls:
    - hosts:
        - factorio.{{ $.Values.baseDomain }}
      secretName: factorio-ingress-tls
  rules:
    - host: factorio.{{ $.Values.baseDomain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: factorio-metrics
                port:
                  number: 9100
