---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Frame-Options SAMEORIGIN;
      add_header Referrer-Policy same-origin;
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options nosniff;
      add_header Content-Security-Policy "frame-ancestors 'self'; default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; style-src 'self'; base-uri 'self'; form-action 'self';" always;
spec:
  tls:
    - hosts:
        - niucraft.barrelmaker.dev
        - motocraft.barrelmaker.dev
      secretName: minecraft-ingress-tls
  rules:
    - host: niucraft.barrelmaker.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: niucraft-minecraft-extras
                port:
                  number: 8123
          - pathType: Prefix
            path: "/metrics"
            backend:
              service:
                name: niucraft-minecraft-extras
                port:
                  number: 9225
    - host: motocraft.barrelmaker.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: motocraft-minecraft-extras
                port:
                  number: 8123
          - pathType: Prefix
            path: "/metrics"
            backend:
              service:
                name: motocraft-minecraft-extras
                port:
                  number: 9225
