---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuma
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuerName }}
    nginx.ingress.kubernetes.io/custom-headers: {{ $.Release.Namespace }}/kuma-custom-headers
spec:
  ingressClassName: {{ $.Values.ingressClass }}
  tls:
    - hosts:
        - kuma.{{ $.Values.baseDomain }}
      secretName: kuma-ingress-tls
  rules:
    - host: kuma.{{ $.Values.baseDomain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ $.Values.externalName }}
                port:
                  number: 3001
