---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuerName }}
    nginx.ingress.kubernetes.io/server-snippet: |
      {{- $.Values.securityHeaders | nindent 6 }}
      add_header Content-Security-Policy "frame-ancestors 'self'; default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self'; connect-src 'self' https://grafana.com; img-src 'self' data:; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self';" always;
spec:
  tls:
    - hosts:
        - grafana.{{ $.Values.baseDomain }}
      secretName: grafana-ingress-tls
  rules:
    - host: grafana.{{ $.Values.baseDomain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: grafana-external
                port:
                  number: 80
