---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuerName }}
    nginx.ingress.kubernetes.io/custom-headers: {{ $.Release.Namespace }}/minecraft-custom-headers
spec:
  ingressClassName: {{ $.Values.ingressClass }}
  tls:
    - hosts:
        - niucraft.{{ $.Values.baseDomain }}
      secretName: minecraft-ingress-tls
  rules:
    - host: niucraft.{{ $.Values.baseDomain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: niucraft-minecraft-extras
                port:
                  number: 8123
          - pathType: Prefix
            path: "/metrics"
            backend:
              service:
                name: niucraft-minecraft-extras
                port:
                  number: 9225
