---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuerName }}
    nginx.ingress.kubernetes.io/server-snippet: |
      {{- $.Values.securityHeaders | nindent 6 }}
      add_header Content-Security-Policy "frame-ancestors 'self'; default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; base-uri 'self'; form-action 'self';" always;
spec:
  tls:
    - hosts:
        - {{ $.Values.baseDomain }}
      secretName: main-ingress-tls
  rules:
    - host: {{ $.Values.baseDomain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: website
                port:
                  number: 80
