---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Frame-Options SAMEORIGIN;
      add_header Referrer-Policy same-origin;
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options nosniff;
      add_header Content-Security-Policy "frame-ancestors 'self'; default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; base-uri 'self'; form-action 'self';" always;
spec:
  tls:
    - hosts:
        - barrelmaker.dev
        - dotfiles.barrelmaker.dev
        - friendbot.barrelmaker.dev
        - kuma.barrelmaker.dev
      secretName: main-ingress-tls
  rules:
    - host: barrelmaker.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: proxy
                port:
                  number: 80
    - host: dotfiles.barrelmaker.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: proxy
                port:
                  number: 80
    - host: friendbot.barrelmaker.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: friendbot
                port:
                  number: 8000
    - host: kuma.barrelmaker.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kuma-external
                port:
                  number: 80
