---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotfiles
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuerName }}
    nginx.ingress.kubernetes.io/rewrite-target: https://raw.githubusercontent.com/barrelmaker97/dotfiles/master/bin/updot
spec:
  ingressClassName: {{ $.Values.ingressClass }}
  tls:
    - hosts:
        - dotfiles.{{ $.Values.baseDomain }}
      secretName: dotfiles-ingress-tls
  rules:
    - host: dotfiles.{{ $.Values.baseDomain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: website
                port:
                  number: 80
