---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuerName }}
    nginx.ingress.kubernetes.io/custom-headers: {{ $.Release.Namespace }}/jellyfin-custom-headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_hide_header Access-Control-Allow-Origin;
spec:
  ingressClassName: {{ $.Values.ingressClass }}
  tls:
    - hosts:
        - jellyfin.{{ $.Values.baseDomain }}
      secretName: jellyfin-ingress-tls
  rules:
    - host: jellyfin.{{ $.Values.baseDomain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
