---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuma-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Frame-Options SAMEORIGIN;
      add_header Referrer-Policy same-origin;
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options nosniff;
      add_header Content-Security-Policy "frame-ancestors 'self'; default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' data:; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self';" always;
spec:
  tls:
    - hosts:
        - kuma.barrelmaker.dev
      secretName: kuma-ingress-tls
  rules:
    - host: kuma.barrelmaker.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kuma-external
                port:
                  number: 80
