---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "factorio.fullname" . }}-config
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "server-settings.json").AsConfig | indent 2 }}
