---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio.fullname" . }}
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "factorio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "factorio.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: factorio
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: factorio
              containerPort: 34197
      {{- if .Values.saveLocation }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: /factorio
      {{- end }}
      {{- if .Values.saveLocation }}
      volumes:
        - name: "{{ .Release.Name }}-data"
          hostPath:
            path: "{{ .Values.saveLocation }}/{{ .Release.Name }}-data"
            type: DirectoryOrCreate
      {{- end }}
