---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio.fullname" . }}
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "factorio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "factorio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "factorio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: factorio
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: factorio
              containerPort: 34197
          resources:
            {{- toYaml .Values.resources.factorio | nindent 12 }}
          volumeMounts:
            - name: savedata
              mountPath: /factorio
        {{- if .Values.metrics }}
        - name: metrics
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.metricsImage.repository }}:{{ .Values.metricsImage.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--collector.disable-defaults"
            - "--collector.textfile"
            - "--collector.textfile.directory=/factorio/script-output/graftorio2"
          ports:
            - name: metrics
              containerPort: 9100
          resources:
            {{- toYaml .Values.resources.metrics | nindent 12 }}
          volumeMounts:
            - name: savedata
              mountPath: /factorio
        {{- end }}
      volumes:
        - name: savedata
          persistentVolumeClaim:
            claimName: {{ include "factorio.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
