---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "factorio.fullname" . }}
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClassName.config }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
