---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorio.fullname" . }}-password
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.server.password | b64enc | quote }}
