{{- if .Values.metrics }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio.fullname" . }}-metrics
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "factorio.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
{{- end }}
