---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-game
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      {{- if .Values.serverPort }}
      nodePort: {{ .Values.serverPort }}
      {{- end }}
