{{- if or .Values.dynmap .Values.metrics }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-extras
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
{{- if .Values.dynmap }}
    - name: dynmap
      protocol: TCP
      port: 8123
      targetPort: 8123
{{- end }}
{{- if .Values.metrics }}
    - name: metrics
      protocol: TCP
      port: 9225
      targetPort: 9225
{{- end }}
{{- end }}
