{{- if .Values.certificate.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "satisfactory.fullname" . }}
  labels:
    {{- include "satisfactory.labels" . | nindent 4 }}
spec:
  secretName: {{ include "satisfactory.fullname" . }}
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
    kind: {{ .Values.certificate.issuerKind }}
  commonName: {{ .Values.certificate.domain }}
  dnsNames:
    - {{ .Values.certificate.domain }}
{{- end }}
