---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "satisfactory.fullname" . }}
  labels:
    {{- include "satisfactory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "satisfactory.selectorLabels" . | nindent 4 }}
  ports:
    - name: satisfactory-1
      protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: 2456
    - name: satisfactory-2
      protocol: UDP
      port: {{ add .Values.service.port 1 }}
      targetPort: 2457
