---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "minecraft.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minecraft.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: minecraft
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: EULA
              value: {{ .Values.properties.eula | quote }}
            - name: MODE
              value: {{ .Values.properties.gamemode | quote }}
            - name: DIFFICULTY
              value: {{ .Values.properties.difficulty | quote }}
            - name: SERVER_NAME
              value: {{ .Values.properties.serverName | quote }}
            - name: MOTD
              value: {{ .Values.properties.motd | quote }}
            - name: SPAWN_PROTECTION
              value: {{ .Values.properties.spawnProtection | quote }}
            - name: FORCE_GAMEMODE
              value: {{ .Values.properties.forceGamemode | quote }}
            - name: TZ
              value: {{ .Values.properties.timezone | quote }}
            - name: VERSION
              value: {{ .Values.properties.version | quote }}
            {{- if .Values.properties.viewDistance }}
            - name: VIEW_DISTANCE
              value: {{ .Values.properties.viewDistance | quote }}
            {{- end }}
            {{- if .Values.properties.seed }}
            - name: SEED
              value: {{ .Values.properties.seed | quote }}
            {{- end }}
            {{- if .Values.properties.type }}
            - name: TYPE
              value: {{ .Values.properties.type | quote }}
            {{- end }}
            {{- if not .Values.properties.online }}
            - name: ONLINE_MODE
              value: {{ .Values.properties.online | quote }}
            {{- end }}
            {{- if .Values.properties.ops }}
            - name: OPS
              value: {{ .Values.properties.ops | quote }}
            {{- end }}
            {{- if .Values.properties.memory }}
            - name: MEMORY
              value: {{ .Values.properties.memory | quote }}
            {{- end }}
          ports:
            - name: minecraft
              containerPort: 25565
          {{- if .Values.dynmap }}
            - name: dynmap
              containerPort: 8123
          {{- end }}
          {{- if .Values.metrics }}
            - name: metrics
              containerPort: 9225
          {{- end }}
          {{- if .Values.properties.memory }}
          resources:
            requests:
              memory: {{ .Values.properties.memory }}
          {{- end }}
      {{- if .Values.saveLocation }}
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /data
      volumes:
        - name: {{ .Release.Name }}-data
          hostPath:
            path: "{{ .Values.saveLocation }}/{{ .Release.Name }}-data"
            type: DirectoryOrCreate
      {{- end }}
