---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "minecraft.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minecraft.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minecraft.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: minecraft
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DIFFICULTY
              value: {{ .Values.properties.difficulty | quote }}
            - name: ENFORCE_WHITELIST
              value: {{ .Values.properties.enforceWhitelist | quote }}
            - name: EULA
              value: {{ .Values.properties.eula | quote }}
            - name: FORCE_GAMEMODE
              value: {{ .Values.properties.forceGamemode | quote }}
            - name: MEMORY
              value: {{ .Values.properties.memory | quote }}
            - name: MODE
              value: {{ .Values.properties.gamemode | quote }}
            - name: MOTD
              value: {{ .Values.properties.motd | quote }}
            - name: ONLINE_MODE
              value: {{ .Values.properties.online | quote }}
            - name: OPS
              value: {{ .Values.properties.ops | quote }}
            - name: OVERRIDE_OPS
              value: {{ .Values.properties.overrideOps | quote }}
            - name: OVERRIDE_WHITELIST
              value: {{ .Values.properties.overrideWhitelist | quote }}
            - name: SEED
              value: {{ .Values.properties.seed | quote }}
            - name: SERVER_NAME
              value: {{ .Values.properties.serverName | quote }}
            - name: SPAWN_PROTECTION
              value: {{ .Values.properties.spawnProtection | quote }}
            - name: SPIGET_RESOURCES
              value: {{ .Values.properties.spigetResources | quote }}
            - name: TYPE
              value: {{ .Values.properties.type | quote }}
            - name: TZ
              value: {{ .Values.properties.timezone | quote }}
            - name: USE_AIKAR_FLAGS
              value: {{ .Values.properties.aikarFlags | quote }}
            - name: VERSION
              value: {{ .Values.properties.version | quote }}
            - name: VIEW_DISTANCE
              value: {{ .Values.properties.viewDistance | quote }}
            - name: WHITELIST
              value: {{ .Values.properties.whitelist | quote }}
          livenessProbe:
            exec:
              command:
                - /health.sh
            initialDelaySeconds: 120
          readinessProbe:
            exec:
              command:
                - /health.sh
          ports:
            - name: minecraft
              containerPort: 25565
          {{- if .Values.dynmap }}
            - name: dynmap
              containerPort: 8123
          {{- end }}
          {{- if .Values.metrics }}
            - name: metrics
              containerPort: 9225
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: savedata
              mountPath: /data
      volumes:
        - name: savedata
          persistentVolumeClaim:
            claimName: {{ include "minecraft.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
