{{- if .Values.dynmap.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}-dynmap
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
  ports:
    - name: dynmap
      protocol: TCP
      port: 8123
      targetPort: dynmap
{{- end }}
