---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
  ports:
    - name: dynmap
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: metrics
      protocol: TCP
      port: 9225
      targetPort: 9225
