---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "minecraft.fullname" . }}-extras
  selector:
    matchLabels:
      {{- include "minecraft.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minecraft.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minecraft.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: minecraft
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DIFFICULTY
              value: {{ .Values.properties.difficulty | quote }}
            - name: ENFORCE_WHITELIST
              value: {{ .Values.properties.enforceWhitelist | quote }}
            - name: EULA
              value: {{ .Values.properties.eula | quote }}
            - name: FORCE_GAMEMODE
              value: {{ .Values.properties.forceGamemode | quote }}
            - name: MEMORY
              value: {{ .Values.properties.memory | quote }}
            - name: MODE
              value: {{ .Values.properties.gamemode | quote }}
            - name: MOTD
              value: {{ .Values.properties.motd | quote }}
            - name: ONLINE_MODE
              value: {{ .Values.properties.online | quote }}
            - name: OPS
              value: {{ .Values.properties.ops | quote }}
            - name: EXISTING_OPS_FILE
              value: {{ .Values.properties.existingOps | quote }}
            - name: EXISTING_WHITELIST_FILE
              value: {{ .Values.properties.existingWhitelist | quote }}
            - name: PAPER_CHANNEL
              value: {{ .Values.properties.paperChannel | quote }}
            - name: SEED
              value: {{ .Values.properties.seed | quote }}
            - name: SERVER_NAME
              value: {{ .Values.properties.serverName | quote }}
            - name: SPAWN_PROTECTION
              value: {{ .Values.properties.spawnProtection | quote }}
            - name: SPIGET_RESOURCES
              value: {{ .Values.properties.spigetResources | quote }}
            - name: MODRINTH_PROJECTS
              value: {{ .Values.properties.modrinthProjects | quote }}
            - name: TYPE
              value: {{ .Values.properties.type | quote }}
            - name: TZ
              value: {{ .Values.properties.timezone | quote }}
            - name: USE_AIKAR_FLAGS
              value: {{ .Values.properties.aikarFlags | quote }}
            - name: VERSION
              value: {{ .Values.properties.version | quote }}
            - name: VIEW_DISTANCE
              value: {{ .Values.properties.viewDistance | quote }}
            - name: WHITELIST
              value: {{ .Values.properties.whitelist | quote }}
          startupProbe:
            exec:
              command:
                - mc-health
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - mc-health
          readinessProbe:
            exec:
              command:
                - mc-health
          ports:
            - name: minecraft
              containerPort: 25565
          {{- if .Values.dynmap.enabled }}
            - name: dynmap
              containerPort: 8123
          {{- end }}
          {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 9225
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: savedata
              mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dynmap.enabled }}
      volumes:
        - name: dynmap-config
          configMap:
            name: {{ include "minecraft.fullname" . }}-dynmap
            defaultMode: 0644
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: savedata
      spec:
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
