{
 "title": "Power",
 "tags": [ "HomeLab" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "elec_price", "label": "Cost per kWh", "query": "${VAR_ELEC_PRICE}" }
  ]
 },
 "panels": [
  {
   "title": "Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ups_battery_charge", "legendFormat": "Charge" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_status", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ups_battery_runtime", "legendFormat": "Runtime" }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(ups_load[1d])/100*24*$elec_price",
     "legendFormat": "Daily"
    },
    {
     "expr": "avg_over_time(ups_load[1w])/100*24*7*$elec_price",
     "legendFormat": "Weekly"
    },
    {
     "expr": "avg_over_time(ups_load[30d])/100*24*30*$elec_price",
     "legendFormat": "Monthly"
    },
    {
     "expr": "avg_over_time(ups_load[30d])/100*24*365*$elec_price",
     "legendFormat": "Yearly"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ups_load", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_input_voltage", "legendFormat": "Input" }
   ]
  },
  {
   "title": "Cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg_over_time(ups_load[1d])/100*24*$elec_price",
     "legendFormat": "Daily"
    }
   ]
  }
 ]
}