{
 "title": "Power",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "elec_price", "label": "Cost per kWh", "query": "0.14" }
  ]
 },
 "panels": [
  {
   "title": "Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ups_battery_charge", "legendFormat": "Charge" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_status", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "avg(ups_battery_runtime)", "legendFormat": "Runtime" }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(job) (avg_over_time(ups_load[24h])) / 100 * 24) * $elec_price",
     "legendFormat": "Daily"
    },
    { "expression": "$A * 7", "type": "math" },
    { "expression": "$A * 30", "type": "math" },
    { "expression": "$A * 365", "type": "math" }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "avg by(job) (ups_load)", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg by(job) (ups_input_voltage)",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg by(job) (avg_over_time(ups_load[1h]))/100*24*$elec_price",
     "legendFormat": "Daily"
    }
   ]
  }
 ]
}