---
apiVersion: v2
name: obscura
description: A Helm chart for Obscura Server
type: application
version: 0.14.1
# renovate: image=ghcr.io/obscura-messaging/obscura-server
appVersion: 0.9.6
maintainers:
  - name: barrelmaker97
    email: nolancooper97@gmail.com
    url: barrelmaker.dev
dependencies:
  - name: postgresql
    version: ~18.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rustfs
    version: 1.0.1
    repository: https://charts.rustfs.com
    condition: rustfs.enabled
  - name: valkey
    version: ~0.9.0
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
